language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=trunk

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
